name: fingo_app
description: "Fingerprint Recognition"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: 
  image_picker_web: 
  image_cropper: ^6.0.0
  photo_editor_sdk: ^3.1.0
  imgly_sdk: ^3.1.0
  flutter_easyloading: ^3.0.5
  image_editor_plus: ^1.0.6
  path_provider: ^2.1.3
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fingerprint.gif
    - lib/assets/fing.png
    - lib/assets/12.png
    - lib/assets/finger.png
    - lib/assets/fingerprint_bg.png
