name: fingo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+3 
  image_picker_web: ^3.1.1
  image_cropper: ^4.0.1
  photo_editor_sdk: ^3.1.0
  imgly_sdk: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fingerprint.gif
